### ISSUE TITLE
PlayerJoinEventError

### ISSUE THREAD

**Issue by riccaz** [morelaid/StreamDrops#6]
![IMG-20230428-WA0019](https://user-images.githubusercontent.com/82407454/235288319-b9f34652-7981-496c-9ab1-9e3a5cd9e3b8.jpg)

**Comment by morelaid** [comment]
Please use one of my offered support options. By using other ways you make my work more difficult and work against my workflow.

There are two ways to solve your issue:
1. execute "/sd reload force".
2. if step 1 does not help, then do a clean server reboot.

If this occurs more often, you can take a closer look, but nasty steps will solve the issue
