### ISSUE TITLE
More a question than an issue: how can i drop a custom item with lore ?

### ISSUE THREAD

**Issue by nnnarvaez** [morelaid/StreamDrops#7]
Lets say i want to give a efi 7 pickaxe with all enchanments as drop should i just:

`- give %player% diamond_pickaxe{display:{Lore:["\"Magical pick not an axe\""]},Enchantments:[{id:efficiency,lvl:7},{id:unbreaking,lvl:3},{id:mending,lvl:1}]} 1 | sdprivate %player% got &6a magical PickAxe$&f! | sendtwitch`

and is there a way to increase the rarity of such drop ?

**Comment by morelaid** [comment]
Please use the support options I offer. This works against my processes and costs more work and can easily be overlooked unintentionally.

The DropChance can be influenced by the number of drop commands. The same command more often = higher chance.
All commands that you can enter in the console can be executed. If a command can be executed in the console, this is also possible with the plugin.

I close this request here, for further questions please use the support options offered by me 😃
